export enum EmapActions {
  Zoom = 0,
  ZoomInWithRectangle = 1,
  ZoomOutWithRectangle = 2,
  Pan = 3,
  FullExtent = 4,
  NextExtent = 5,
  PreviousExtent = 6,
  XYCoordinate = 7,
  DrawPoint = 8,
  DrawLine = 9,
  DrawPolygon = 10,
  DrawRectangle = 11,
  DrawArrow = 12,
  DrawEllipse = 13,
  DrawCircle = 14,
  DrawFreehandPolyLine = 15,
  ClearGraphic = 16,
  DeleteDraw = 17,
  EditElement = 18,
  Identify = 19,
  DrawText = 20,
  FlashToGeometry = 21,
  OverViewMap = 22,
  Select = 23,
  RefreshMap = 24,
  ExportMap = 25,
  MeasureLine = 26,
  MeasurePolygon = 27,
  GeoZoom = 28,
  Bookmark = 29,
  SetAI = 30,
  SeekPredio = 31,
  SeekPredioGeometry = 32,
  RiskZone = 33,
  RiskZoneGeometry = 34,
  ZoomToGeometry = 35,
  AddGeometry = 36,
  CallModal = 37,
  ZoomToGeometries = 38,
  AvailableOperator = 39,
  AvailableOperatorGeometry = 40,
  startProcess = 41,
  stopProcess = 42,
  ObviateValves = 43,
  ObviateValvesGeometry = 44,
  DeleteGeometries = 45,
  ManejoPrensas = 46,
  ManejoPrensasGeometry = 47,
  ModifyAffectedUsers = 48,
  ModifyAffectedUsersGeometry = 49,
  SecurityRisk = 50,
  SecurityManzanaGeometry = 51,
  OrderManagement = 52,
  OrderManzanaGeometry = 53
}

export enum EMeasureActions {
  MeasureLine = 1,
  MeasurePolygon = 2
}

export enum Emodal {
  ViewSelection = 1,
  DrawColorComponent = 2,
  AddressSearchComponent = 3,
  ChangeStratumComponent = 4,
  ConsultComponent = 5,
  SearchesComponent = 6,
  ThematicMapComponent = 7,
  ViewInformation = 8
}
